// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: cloudstate/entity.proto
// </auto-generated>
// Original file comments:
// Copyright 2019 Lightbend Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// gRPC interface for Event Sourced Entity user functions.
//
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Cloudstate {
  /// <summary>
  /// Entity discovery service.
  /// </summary>
  public static partial class EntityDiscovery
  {
    static readonly string __ServiceName = "cloudstate.EntityDiscovery";

    static readonly grpc::Marshaller<global::Cloudstate.ProxyInfo> __Marshaller_cloudstate_ProxyInfo = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Cloudstate.ProxyInfo.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Cloudstate.EntitySpec> __Marshaller_cloudstate_EntitySpec = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Cloudstate.EntitySpec.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Cloudstate.UserFunctionError> __Marshaller_cloudstate_UserFunctionError = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Cloudstate.UserFunctionError.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);

    static readonly grpc::Method<global::Cloudstate.ProxyInfo, global::Cloudstate.EntitySpec> __Method_discover = new grpc::Method<global::Cloudstate.ProxyInfo, global::Cloudstate.EntitySpec>(
        grpc::MethodType.Unary,
        __ServiceName,
        "discover",
        __Marshaller_cloudstate_ProxyInfo,
        __Marshaller_cloudstate_EntitySpec);

    static readonly grpc::Method<global::Cloudstate.UserFunctionError, global::Google.Protobuf.WellKnownTypes.Empty> __Method_reportError = new grpc::Method<global::Cloudstate.UserFunctionError, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "reportError",
        __Marshaller_cloudstate_UserFunctionError,
        __Marshaller_google_protobuf_Empty);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Cloudstate.EntityReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of EntityDiscovery</summary>
    [grpc::BindServiceMethod(typeof(EntityDiscovery), "BindService")]
    public abstract partial class EntityDiscoveryBase
    {
      /// <summary>
      /// Discover what entities the user function wishes to serve.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::Cloudstate.EntitySpec> discover(global::Cloudstate.ProxyInfo request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Report an error back to the user function. This will only be invoked to tell the user function
      /// that it has done something wrong, eg, violated the protocol, tried to use an entity type that
      /// isn't supported, or attempted to forward to an entity that doesn't exist, etc. These messages
      /// should be logged clearly for debugging purposes.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> reportError(global::Cloudstate.UserFunctionError request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for EntityDiscovery</summary>
    public partial class EntityDiscoveryClient : grpc::ClientBase<EntityDiscoveryClient>
    {
      /// <summary>Creates a new client for EntityDiscovery</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public EntityDiscoveryClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for EntityDiscovery that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public EntityDiscoveryClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected EntityDiscoveryClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected EntityDiscoveryClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Discover what entities the user function wishes to serve.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Cloudstate.EntitySpec discover(global::Cloudstate.ProxyInfo request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return discover(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Discover what entities the user function wishes to serve.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Cloudstate.EntitySpec discover(global::Cloudstate.ProxyInfo request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_discover, null, options, request);
      }
      /// <summary>
      /// Discover what entities the user function wishes to serve.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Cloudstate.EntitySpec> discoverAsync(global::Cloudstate.ProxyInfo request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return discoverAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Discover what entities the user function wishes to serve.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Cloudstate.EntitySpec> discoverAsync(global::Cloudstate.ProxyInfo request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_discover, null, options, request);
      }
      /// <summary>
      /// Report an error back to the user function. This will only be invoked to tell the user function
      /// that it has done something wrong, eg, violated the protocol, tried to use an entity type that
      /// isn't supported, or attempted to forward to an entity that doesn't exist, etc. These messages
      /// should be logged clearly for debugging purposes.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Google.Protobuf.WellKnownTypes.Empty reportError(global::Cloudstate.UserFunctionError request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return reportError(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Report an error back to the user function. This will only be invoked to tell the user function
      /// that it has done something wrong, eg, violated the protocol, tried to use an entity type that
      /// isn't supported, or attempted to forward to an entity that doesn't exist, etc. These messages
      /// should be logged clearly for debugging purposes.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Google.Protobuf.WellKnownTypes.Empty reportError(global::Cloudstate.UserFunctionError request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_reportError, null, options, request);
      }
      /// <summary>
      /// Report an error back to the user function. This will only be invoked to tell the user function
      /// that it has done something wrong, eg, violated the protocol, tried to use an entity type that
      /// isn't supported, or attempted to forward to an entity that doesn't exist, etc. These messages
      /// should be logged clearly for debugging purposes.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> reportErrorAsync(global::Cloudstate.UserFunctionError request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return reportErrorAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Report an error back to the user function. This will only be invoked to tell the user function
      /// that it has done something wrong, eg, violated the protocol, tried to use an entity type that
      /// isn't supported, or attempted to forward to an entity that doesn't exist, etc. These messages
      /// should be logged clearly for debugging purposes.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> reportErrorAsync(global::Cloudstate.UserFunctionError request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_reportError, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override EntityDiscoveryClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new EntityDiscoveryClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(EntityDiscoveryBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_discover, serviceImpl.discover)
          .AddMethod(__Method_reportError, serviceImpl.reportError).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, EntityDiscoveryBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_discover, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Cloudstate.ProxyInfo, global::Cloudstate.EntitySpec>(serviceImpl.discover));
      serviceBinder.AddMethod(__Method_reportError, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Cloudstate.UserFunctionError, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.reportError));
    }

  }
}
#endregion
