// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: cloudstate/entity_key.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Cloudstate {

  /// <summary>Holder for reflection information generated from cloudstate/entity_key.proto</summary>
  public static partial class EntityKeyReflection {

    #region Descriptor
    /// <summary>File descriptor for cloudstate/entity_key.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EntityKeyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChtjbG91ZHN0YXRlL2VudGl0eV9rZXkucHJvdG8SCmNsb3Vkc3RhdGUaIGdv",
            "b2dsZS9wcm90b2J1Zi9kZXNjcmlwdG9yLnByb3RvOjMKCmVudGl0eV9rZXkS",
            "HS5nb29nbGUucHJvdG9idWYuRmllbGRPcHRpb25zGNKGAyABKAhCDwoNaW8u",
            "Y2xvdWRzdGF0ZWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.Reflection.DescriptorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pb::Extension[] { EntityKeyExtensions.EntityKey }, null));
    }
    #endregion

  }
  /// <summary>Holder for extension identifiers generated from the top level of cloudstate/entity_key.proto</summary>
  internal static partial class EntityKeyExtensions {
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, bool> EntityKey =
      new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, bool>(50002, pb::FieldCodec.ForBool(400016, false));
  }

}

#endregion Designer generated code
