// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: frontend/cloudstate/entity_key.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace io.cloudstate {

  /// <summary>Holder for reflection information generated from frontend/cloudstate/entity_key.proto</summary>
  public static partial class EntityKeyReflection {

    #region Descriptor
    /// <summary>File descriptor for frontend/cloudstate/entity_key.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EntityKeyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiRmcm9udGVuZC9jbG91ZHN0YXRlL2VudGl0eV9rZXkucHJvdG8SCmNsb3Vk",
            "c3RhdGUaIGdvb2dsZS9wcm90b2J1Zi9kZXNjcmlwdG9yLnByb3RvOjMKCmVu",
            "dGl0eV9rZXkSHS5nb29nbGUucHJvdG9idWYuRmllbGRPcHRpb25zGNKGAyAB",
            "KAhCHwoNaW8uY2xvdWRzdGF0ZaoCDWlvLmNsb3Vkc3RhdGViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { pbr::FileDescriptor.DescriptorProtoFileDescriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
